# -*- coding: utf-8 -*-
"""Ml_BloodDonor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zbfnzx_N854H7N9IYptwpFks88YVvjzr
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, BaggingClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import RFE
from collections import Counter
from imblearn.over_sampling import SMOTE
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import TomekLinks
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline

from sklearn.metrics import hamming_loss
from sklearn.metrics import jaccard_score
from sklearn.metrics import log_loss
from sklearn.metrics import matthews_corrcoef


from sklearn.ensemble import VotingClassifier

from google.colab import files


uploaded = files.upload()

# Assuming the file is named 'your_file.xlsx'
df = pd.read_csv('BLOOD_DONOR_DATA_edit1.csv')
# Check the column names to ensure 'Freq' exists
print(df.columns)
# df=pd.read_excel('ForEditing2.xlsx')  # Reading the data
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows',None)

df.shape  # number of columns and rows

df = df.sample(frac = 1)  # Shuffle rows

df.isna().sum()  # checking for null values

# Check data types of columns
print(df.dtypes)
#fillling empty values with median
df = df.fillna(df.median())
df.isna().sum()

# copy the data
df_max_scaled = df.copy()

# apply normalization techniques
for column in df_max_scaled.columns:
    df_max_scaled[column] = df_max_scaled[column]  / df_max_scaled[column].abs().max()

# view normalized data
display(df_max_scaled)

from imblearn.over_sampling import BorderlineSMOTE
df = df.astype('float64')

x = df.drop('CameAgain', axis=1)
x = df.drop('FreqDonation', axis=1)
y = df['CameAgain'].astype('int')

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 1)
oversample = BorderlineSMOTE()
x_train, y_train = oversample.fit_resample(x_train, y_train)

"""# **Random Forest**"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
rf = RandomForestClassifier()

# Fit the Random Forest on the training data to determine feature importance
rf.fit(x_train, y_train)
param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100, 110],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200, 300, 1000]
}

rfclassifier = RandomizedSearchCV(
    rf, param_distributions=param_grid, n_iter=10,
    cv=5, n_jobs=-1, random_state=42
)
rfclassifier.fit(x_train, y_train)
rfclassifier.best_params_

from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, precision_score, recall_score
from sklearn.metrics import classification_report, average_precision_score, accuracy_score, f1_score
y_pred = rfclassifier.predict(x_test)
y_proba = rfclassifier.predict_proba(x_test)[:,1]

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# RandomForest summary
print('\n')
accuracy = round(accuracy_score(y_test, y_pred),2)
print("accuracy",accuracy)
precision = round(precision_score(y_test, y_pred, average='micro'),2)
print("precision",precision)
recall = round(recall_score(y_test, y_pred, average='micro'),2)
print("recall",recall)
# precision_recall = round(average_precision_score(y_test, y_proba, average='weighted'),2)
auc = round(roc_auc_score(y_test, y_proba, average='weighted', multi_class='ovr'), 2)
print('AUC: {}'.format(round(roc_auc_score(y_test, y_proba),2)))
print('Precision-Recall: {}'.format(round(average_precision_score(y_test, y_proba),2)))
f1 = round(f1_score(y_test, y_pred, average='weighted'),2)
print('f1 score::',f1)
fpr, tpr, _ = roc_curve(y_test,  y_pred)
auc = round(roc_auc_score(y_test, y_proba),2)


print("hamming loss")
print(hamming_loss(y_test, y_pred))
print("jaccord score")
print(jaccard_score(y_test, y_pred))
print("log loss")
print(log_loss(y_test,y_pred))
print("mathews correlation coefficient")
print(matthews_corrcoef(y_test, y_pred))


fig = plt.figure()

# Set titles for the figure and the subplot respectively
fig.suptitle('(a)', fontsize=14, fontweight='bold')
ax = plt.axes()
ax.set_facecolor('beige')

plt.plot(fpr,tpr,color='xkcd:black',label='Random forest  AUC: '+str(auc))
plt.legend(loc=4)
plt.grid(True)
plt.plot([0, 1], [0, 1], color='blue', linestyle='-.')
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.savefig("AUC RandomForest", dpi=800,bbox_inches = 'tight')

plt.show()

from imblearn.over_sampling import BorderlineSMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Assuming 'df' contains your dataset with appropriate preprocessing
# Define features (x) and target variable (y)
x = df.drop(['CameAgain', 'FreqDonation'], axis=1)
y = df['CameAgain'].astype('int')

# Split data into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

# Apply oversampling technique (BorderlineSMOTE)
oversample = BorderlineSMOTE()
x_train_resampled, y_train_resampled = oversample.fit_resample(x_train, y_train)

# Initialize Random Forest Classifier
rf = RandomForestClassifier()

# Fit the Random Forest on the resampled training data to determine feature importance
rf.fit(x_train_resampled, y_train_resampled)

# Select features based on importance, excluding the target variable and 'FreqDonation'
feature_selector = SelectFromModel(rf, threshold=-np.inf, max_features=5)
x_train_selected = feature_selector.fit_transform(x_train_resampled, y_train_resampled)
x_test_selected = feature_selector.transform(x_test)

# Print selected features information for training set
print("Number of selected features:", x_train_selected.shape[1])
print("Selected Features:")
selected_feature_indices = feature_selector.get_support(indices=True)
for idx in selected_feature_indices:
    print(f"Feature {idx}: {x.columns[idx]}")
# Store the top 5 features in an array called top_15
top_15 = x.columns[selected_feature_indices].tolist()
print("Top 5 Features:", top_15)
# # Define parameter grid for RandomizedSearchCV
# param_grid = {
#     'bootstrap': [True],
#     'max_depth': [80, 90, 100, 110],
#     'max_features': [2, 3],
#     'min_samples_leaf': [3, 4, 5],
#     'min_samples_split': [8, 10, 12],
#     'n_estimators': [100, 200, 300, 1000]
# }

# # Initialize RandomizedSearchCV
# rfclassifier = RandomizedSearchCV(
#     rf, param_distributions=param_grid, n_iter=10,
#     cv=5, n_jobs=-1, random_state=42
# )

# # Fit RandomizedSearchCV with the selected features and resampled target variable
# rfclassifier.fit(x_train_selected, y_train_resampled)

# # Print best parameters found
# print("Best Parameters:", rfclassifier.best_params_)

# # Predict on test set
# y_pred = rfclassifier.predict(x_test_selected)

# # Print evaluation metrics
# print("\nConfusion Matrix:")
# print(confusion_matrix(y_test, y_pred))

# print("\nClassification Report:")
# print(classification_report(y_test, y_pred))

"""# **Logistic Regression**"""

#Logistic Regression
# Create the parameter grid based on the results of random search
param_grid = {
    'penalty': ['l2'],
    'C': [0.001,0.01,0.1,1,10,100,1000]
}

# Create a based model
lr = LogisticRegression()
# Fit the Random Forest on the training data to determine feature importance
rf.fit(x_train, y_train)

# Select features based on importance
feature_selector = SelectFromModel(rf, prefit=True)
x_train_selected = feature_selector.transform(x_train)
x_test_selected = feature_selector.transform(x_test)
# Instantiate the grid search model
lrClassifier = RandomizedSearchCV(estimator = lr, param_distributions = param_grid,
                          cv = 3, n_jobs = -1, verbose = 2)

lrClassifier.fit(x_train, y_train)
lrClassifier.best_params_

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, roc_auc_score,
    average_precision_score, f1_score, roc_curve, hamming_loss,
    jaccard_score, log_loss, matthews_corrcoef
)

y_pred = lrClassifier.predict(x_test)
y_proba = lrClassifier.predict_proba(x_test)[:,1]

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
# printing number selected features
print(f"Number of selected features: {x_train_selected.shape[1]}")
print('\n')
accuracy = round(accuracy_score(y_test, y_pred),2)
print("accuracy",accuracy)
precision = round(precision_score(y_test, y_pred, average='micro'),2)
print("precision",precision)
recall = round(recall_score(y_test, y_pred, average='micro'),2)
print("recall",recall)
# precision_recall = round(average_precision_score(y_test, y_proba, average='weighted'),2)
auc = round(roc_auc_score(y_test, y_proba, average='weighted', multi_class='ovr'), 2)
print('AUC: {}'.format(round(roc_auc_score(y_test, y_proba),2)))
print('Precision-Recall: {}'.format(round(average_precision_score(y_test, y_proba),2)))
f1 = round(f1_score(y_test, y_pred, average='weighted'),2)
print('f1 score::',f1)
fpr, tpr, _ = roc_curve(y_test,  y_pred)
auc = round(roc_auc_score(y_test, y_proba),2)
fpr, tpr, _ = roc_curve(y_test,  y_pred,)
# auc = round(roc_auc_score(y_test, y_proba),2)
print("hamming loss")
print(hamming_loss(y_test, y_pred))
print("jaccord score")
print(jaccard_score(y_test, y_pred))
print("log loss")
print(log_loss(y_test,y_pred))
print("mathews correlation coefficient")
print(matthews_corrcoef(y_test, y_pred))

fig = plt.figure()

# Set titles for the figure and the subplot respectively
fig.suptitle('(a)', fontsize=14, fontweight='bold')
ax = plt.axes()
ax.set_facecolor('beige')

plt.plot(fpr,tpr,color='xkcd:black',label='Logistic Regression  AUC: '+str(auc))
plt.legend(loc=4)
plt.grid(True)
plt.plot([0, 1], [0, 1], color='blue', linestyle='-.')
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.savefig("AUC RandomForest", dpi=800,bbox_inches = 'tight')

plt.show()

#Precsiion Recall Curve
from sklearn.metrics import plot_precision_recall_curve
plot_precision_recall_curve(lrClassifier, x_test, y_test,color='xkcd:black', name = '')



plt.grid(True)
plt.plot([0, 1], [0, 1], color='blue', linestyle='-.')
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.legend(loc=4)
plt.grid(True)

plt.savefig("PR curve random forest", dpi=800,bbox_inches = 'tight')


#Confusion Matrix
 #print confusion matrix
cm=confusion_matrix(y_test, y_pred)
plt.figure(figsize=(10,6))
sns.heatmap(cm,annot=True,fmt="d")
sns.heatmap
plt.xlabel('Actual values')
plt.ylabel('Predicted values')
plt.savefig("Confusion Matrix Logistic regression", dpi=800,bbox_inches = 'tight')

"""# **Decission Tree**"""

#Decision Tree
param_grid = {
    'criterion' : ['gini', 'entropy'],
    'max_depth':[4,5,6,7,8,9,10,11,12,15,20,30,40,50,70,90,120,150],
    'min_samples_split' : range(10,500,20),
    'splitter' : ['best', 'random'],
    'min_samples_leaf': [1,5,8,11],
    'max_features': ['log2', 'sqrt','auto']
}

# Create a based model
dt = DecisionTreeClassifier()
# Instantiate the grid search model
dtClassifier = RandomizedSearchCV(estimator = dt, param_distributions = param_grid,
                          cv = 3, n_jobs = -1, verbose = 2)

dtClassifier.fit(x_train, y_train)
dtClassifier.best_params_

y_pred = dtClassifier.predict(x_test)
y_proba = dtClassifier.predict_proba(x_test)[:,1]

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


print("hamming loss")
print(hamming_loss(y_test, y_pred))
print("jaccord score")
print(jaccard_score(y_test, y_pred))
print("log loss")
print(log_loss(y_test,y_pred))
print("mathews correlation coefficient")
print(matthews_corrcoef(y_test, y_pred))

print('\n')
accuracy = round(accuracy_score(y_test, y_pred),2)
print("accuracy",accuracy)
precision = round(precision_score(y_test, y_pred),2)
print("precision",precision)
f1 = round(f1_score(y_test, y_pred, average='weighted'),2)
print('f1 score::',f1)
recall = round(recall_score(y_test, y_pred),2)
print("recall",recall)
precision_recall = round(average_precision_score(y_test, y_proba),2)
auc = round(roc_auc_score(y_test, y_proba),2)
print('AUC: {}'.format(round(roc_auc_score(y_test, y_proba),2)))
print('Precision-Recall: {}'.format(round(average_precision_score(y_test, y_proba),2)))

fpr, tpr, _ = roc_curve(y_test,  y_pred)
auc = round(roc_auc_score(y_test, y_proba),2)


fig = plt.figure()

# Set titles for the figure and the subplot respectively
fig.suptitle('(a)', fontsize=14, fontweight='bold')
ax = plt.axes()
ax.set_facecolor('beige')

plt.plot(fpr,tpr,color='xkcd:black',label='Decision tree  AUC: '+str(auc))
plt.legend(loc=4)
plt.grid(True)
plt.plot([0, 1], [0, 1], color='blue', linestyle='-.')
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.savefig("AUC Decision Tree", dpi=800,bbox_inches = 'tight')

plt.show()




#Precsiion Recall Curve
from sklearn.metrics import plot_precision_recall_curve
plot_precision_recall_curve(dtClassifier, x_test, y_test,color='xkcd:black', name = 'Decision Tree')



plt.grid(True)
plt.plot([0, 1], [0, 1], color='blue', linestyle='-.')
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.legend(loc=4)
plt.grid(True)

plt.savefig("PR curve random forest", dpi=800,bbox_inches = 'tight')


#Confusion Matrix
 #print confusion matrix
cm=confusion_matrix(y_test, y_pred)
plt.figure(figsize=(10,6))
sns.heatmap(cm,annot=True,fmt="d")
sns.heatmap
plt.xlabel('Actual values')
plt.ylabel('Predicted values')
plt.savefig("Confusion Matix Decision Tree", dpi=800,bbox_inches = 'tight')

"""# **Knn Classifier**"""

# # Create a based model
# from sklearn.neighbors import KNeighborsClassifier  # Import KNeighborsClassifier
# from sklearn.model_selection import RandomizedSearchCV  # Import RandomizedSearchCV

# # Create a basic KNN model
# knn = KNeighborsClassifier(algorithm = 'brute')

# k_range = list(range(1, 100))
# param_grid = dict(n_neighbors=k_range)

# # Instantiate the grid search model
# knnClassifier = RandomizedSearchCV(estimator = knn, param_distributions = param_grid,
#                           cv = 3, n_jobs = -1, verbose = 2)

# knnClassifier.fit(x_train, y_train)
# knnClassifier.best_params_
# KNN parameter grid
knn_param_grid = {
    'n_neighbors': list(range(1, 50)),
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']
}

# Feature Selection using RandomForest
x_train_selected = feature_selector.transform(x_train)
x_test_selected = feature_selector.transform(x_test)

# KNN Model and Grid Search
knn = KNeighborsClassifier()
knnClassifier = RandomizedSearchCV(knn, param_distributions=knn_param_grid, cv=3, n_jobs=-1, verbose=2)
knnClassifier.fit(x_train_selected, y_train)

print("Best Parameters:", knnClassifier.best_params_)

# Predictions
y_pred = knnClassifier.predict(x_test_selected)
y_proba = knnClassifier.predict_proba(x_test_selected)[:, 1]

# Metrics
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Number of selected features:", x_train_selected.shape[1])
print("Accuracy:", round(accuracy_score(y_test, y_pred), 2))
print("Precision:", round(precision_score(y_test, y_pred), 2))
print("Recall:", round(recall_score(y_test, y_pred), 2))
print("AUC:", round(roc_auc_score(y_test, y_proba), 2))
print("F1 Score:", round(f1_score(y_test, y_pred, average='weighted'), 2))

# ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_proba)
plt.figure()
plt.plot(fpr, tpr, color='black', label=f'AdaBoost AUC: {round(roc_auc_score(y_test, y_proba), 2)}')
plt.plot([0, 1], [0, 1], linestyle='-.', color='blue')
plt.legend(loc=4)
plt.grid(True)
plt.title("ROC Curve - AdaBoost")
plt.savefig("AUC_AdaBoost.png", dpi=800, bbox_inches='tight')
plt.show()

# Precision-Recall Curve
plot_precision_recall_curve(adClassifier, x_test_selected, y_test, name='AdaBoost')
plt.grid(True)
plt.savefig("PR_Curve_AdaBoost.png", dpi=800, bbox_inches='tight')
plt.show()

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(10, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - AdaBoost')
plt.savefig("Confusion_Matrix_AdaBoost.png", dpi=800, bbox_inches='tight')
plt.show()

"""# **Ada Boost**"""

# param_grid = {
#     'n_estimators': [100, 200, 300, 1000],
#     'learning_rate': [0.0001, 0.001, 0.01, 0.1, 1.0]
# }

# # Create a based model
# ad = AdaBoostClassifier()
# # Instantiate the grid search model
# grid_searchAdaBoostClassifier = RandomizedSearchCV(estimator = ad, param_distributions = param_grid,
#                           cv = 3, n_jobs = -1, verbose = 2)

# grid_searchAdaBoostClassifier.fit(x_train, y_train)
# grid_searchAdaBoostClassifier.best_params_
# AdaBoost parameter grid
adaboost_param_grid = {
    'n_estimators': [100, 200, 300, 1000],
    'learning_rate': [0.0001, 0.001, 0.01, 0.1, 1.0]
}

# Feature Selection using RandomForest
rf = RandomForestClassifier(n_estimators=100)
rf.fit(x_train, y_train)
feature_selector = SelectFromModel(rf, prefit=True)
x_train_selected = feature_selector.transform(x_train)
x_test_selected = feature_selector.transform(x_test)

# AdaBoost Model and Grid Search
ad = AdaBoostClassifier()
adClassifier = RandomizedSearchCV(ad, param_distributions=adaboost_param_grid, cv=3, n_jobs=-1, verbose=2)
adClassifier.fit(x_train_selected, y_train)

print("Best Parameters:", adClassifier.best_params_)

# Predictions
y_pred = adClassifier.predict(x_test_selected)
y_proba = adClassifier.predict_proba(x_test_selected)[:, 1]

# Metrics
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Number of selected features:", x_train_selected.shape[1])
print("Accuracy:", round(accuracy_score(y_test, y_pred), 2))
print("Precision:", round(precision_score(y_test, y_pred), 2))
print("Recall:", round(recall_score(y_test, y_pred), 2))
print("AUC:", round(roc_auc_score(y_test, y_proba), 2))
print("F1 Score:", round(f1_score(y_test, y_pred, average='weighted'), 2))

# ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_proba)
plt.figure()
plt.plot(fpr, tpr, color='black', label=f'AdaBoost AUC: {round(roc_auc_score(y_test, y_proba), 2)}')
plt.plot([0, 1], [0, 1], linestyle='-.', color='blue')
plt.legend(loc=4)
plt.grid(True)
plt.title("ROC Curve - AdaBoost")
plt.savefig("AUC_AdaBoost.png", dpi=800, bbox_inches='tight')
plt.show()

# Precision-Recall Curve
plot_precision_recall_curve(adClassifier, x_test_selected, y_test, name='AdaBoost')
plt.grid(True)
plt.savefig("PR_Curve_AdaBoost.png", dpi=800, bbox_inches='tight')
plt.show()

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(10, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - AdaBoost')
plt.savefig("Confusion_Matrix_AdaBoost.png", dpi=800, bbox_inches='tight')
plt.show()

"""# **Xg Boost**"""

# from xgboost import XGBClassifier

# param_grid = {
#     "learning_rate": (0.05, 0.10, 0.15),
#                         "max_depth": [ 3, 4, 5, 6, 8],
#                         "min_child_weight": [ 1, 3, 5, 7],
#                         "gamma":[ 0.0, 0.1, 0.2],
#                         "colsample_bytree":[ 0.3, 0.4],


#              }

# # Create a based model
# lg = XGBClassifier()
# # Instantiate the grid search model
# xgb = RandomizedSearchCV(estimator = lg, param_distributions = param_grid,
#                           cv = 3, n_jobs = -1, verbose = 2)

# xgb.fit(x_train,y_train)
# xgb.best_params_
# XGBoost parameter grid
xgboost_param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'subsample': [0.8, 1.0]
}

# Feature Selection using RandomForest
x_train_selected = feature_selector.transform(x_train)
x_test_selected = feature_selector.transform(x_test)

# XGBoost Model and Grid Search
xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgbClassifier = RandomizedSearchCV(xgb, param_distributions=xgboost_param_grid, cv=3, n_jobs=-1, verbose=2)
xgbClassifier.fit(x_train_selected, y_train)

print("Best Parameters:", xgbClassifier.best_params_)

# Predictions
y_pred = xgbClassifier.predict(x_test_selected)
y_proba = xgbClassifier.predict_proba(x_test_selected)[:, 1]

# Metrics
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Number of selected features:", x_train_selected.shape[1])
print("Accuracy:", round(accuracy_score(y_test, y_pred), 2))
print("Precision:", round(precision_score(y_test, y_pred), 2))
print("Recall:", round(recall_score(y_test, y_pred), 2))
print("AUC:", round(roc_auc_score(y_test, y_proba), 2))
print("F1 Score:", round(f1_score(y_test, y_pred, average='weighted'), 2))

# ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_proba)
plt.figure()
plt.plot(fpr, tpr, color='black', label=f'AdaBoost AUC: {round(roc_auc_score(y_test, y_proba), 2)}')
plt.plot([0, 1], [0, 1], linestyle='-.', color='blue')
plt.legend(loc=4)
plt.grid(True)
plt.title("ROC Curve - AdaBoost")
plt.savefig("AUC_AdaBoost.png", dpi=800, bbox_inches='tight')
plt.show()

# Precision-Recall Curve
plot_precision_recall_curve(adClassifier, x_test_selected, y_test, name='AdaBoost')
plt.grid(True)
plt.savefig("PR_Curve_AdaBoost.png", dpi=800, bbox_inches='tight')
plt.show()

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(10, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix - AdaBoost')
plt.savefig("Confusion_Matrix_AdaBoost.png", dpi=800, bbox_inches='tight')
plt.show()